export const DEFAULT_FFT_SIZE = 2048;
export const DEFAULT_MEASUREMENTS_COUNT = 10;
export const DEFAULT_INTERVAL_MS = 500;
export const DEFAULT_MIN_CONFIDENCE = 35;
export const DEFAULT_ACTIVITY_RMS_THRESHOLD = 0.02;
export const DRONE_TEMPLATE_KEY_PREFIX = 'DRONE';
