/**
 * AUTO-GENERATED by scripts/build-usercase-mvp-microphone.mjs — do not edit.
 * Default device-scenario for first-time microphone users.
 */
import type { DeviceScenarioDocument } from '@membrana/core';

export const DEFAULT_USERCASE_MVP_MICROPHONE_DOCUMENT = {
  "version": 2,
  "kind": "device-scenario",
  "deviceKind": "microphone",
  "meta": {
    "title": "UserCase MVP microphone (default)",
    "exportedAt": "2026-06-21T08:39:26.354Z"
  },
  "signalGraph": {
    "nodes": [],
    "edges": []
  },
  "scenario": {
    "initial": {
      "entry": "initial-event",
      "nodes": [
        {
          "id": "initial-event",
          "blockKind": "custom",
          "position": {
            "x": -1890.4473160332445,
            "y": -603.8030337318398
          },
          "label": "On start",
          "nodeKind": "event",
          "system": true,
          "eventVariant": "handler"
        },
        {
          "id": "node-get-microphone-mqkpxb3c-5",
          "blockKind": "custom",
          "position": {
            "x": 535.1686504497413,
            "y": -275.8515850500755
          },
          "label": "GetMicrophone",
          "nodeKind": "get-microphone",
          "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
        },
        {
          "id": "node-print-mqksbm4o-3",
          "blockKind": "custom",
          "position": {
            "x": -89.52827350864165,
            "y": -465.68903526964687
          },
          "label": "Print",
          "nodeKind": "print"
        },
        {
          "id": "node-start-streaming-mql556hh-49",
          "blockKind": "custom",
          "position": {
            "x": 1291.57719127356,
            "y": -124.78361738985245
          },
          "label": "StartStreaming",
          "nodeKind": "start-streaming"
        },
        {
          "id": "node-is-valid-mqm9i48b-18",
          "blockKind": "custom",
          "position": {
            "x": -1491.3976992236421,
            "y": -417.45040961706457
          },
          "label": "isValid",
          "nodeKind": "is-valid"
        },
        {
          "id": "node-device-global-mqm9ip17-19",
          "blockKind": "custom",
          "position": {
            "x": -1758.4560472976493,
            "y": -77.87529318378682
          },
          "label": "GetDevice",
          "nodeKind": "device-global"
        },
        {
          "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "blockKind": "custom",
          "position": {
            "x": -703.4560472976507,
            "y": -310.87529318378665
          },
          "label": "journal1",
          "nodeKind": "variable-set",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        },
        {
          "id": "node-get-journal-mqm9j4wy-20",
          "blockKind": "custom",
          "position": {
            "x": -1066.45604729765,
            "y": -246.0752863173316
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        },
        {
          "id": "node-get-journal-mvp-initial-valid-1",
          "blockKind": "custom",
          "position": {
            "x": -1750,
            "y": -242
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        }
      ],
      "edges": [
        {
          "source": "initial-event",
          "sourceHandle": "exec-out",
          "target": "node-is-valid-mqm9i48b-18",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-device-global-mqm9ip17-19",
          "sourceHandle": "device",
          "target": "node-get-journal-mqm9j4wy-20",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-is-valid-mqm9i48b-18",
          "sourceHandle": "exec-false-out",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-journal-mqm9j4wy-20",
          "sourceHandle": "journal",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        },
        {
          "source": "node-device-global-mqm9ip17-19",
          "sourceHandle": "device",
          "target": "node-get-journal-mvp-initial-valid-1",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-get-journal-mvp-initial-valid-1",
          "sourceHandle": "journal",
          "target": "node-is-valid-mqm9i48b-18",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        },
        {
          "source": "initial-event",
          "sourceHandle": "device",
          "target": "node-get-microphone-mqkpxb3c-5",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-get-microphone-mqkpxb3c-5",
          "sourceHandle": "microphone",
          "target": "node-start-streaming-mql556hh-49",
          "targetHandle": "microphone",
          "kind": "data",
          "dataType": "MicrophoneRef"
        },
        {
          "source": "initial-event",
          "sourceHandle": "datetime",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "DateTime"
        },
        {
          "source": "node-is-valid-mqm9i48b-18",
          "sourceHandle": "exec-true-out",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-print-mqksbm4o-3",
          "sourceHandle": "exec-out",
          "target": "node-get-microphone-mqkpxb3c-5",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-microphone-mqkpxb3c-5",
          "sourceHandle": "exec-out",
          "target": "node-start-streaming-mql556hh-49",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "sourceHandle": "exec-out",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "exec-in",
          "kind": "exec"
        }
      ]
    },
    "onConnect": {
      "entry": "on-connect-event",
      "nodes": [
        {
          "id": "on-connect-event",
          "blockKind": "custom",
          "position": {
            "x": -143.74603485864776,
            "y": -65.2871627314024
          },
          "label": "On connect",
          "nodeKind": "event",
          "system": true,
          "eventVariant": "handler"
        },
        {
          "id": "node-is-valid-mqm97w5v-17",
          "blockKind": "custom",
          "position": {
            "x": 170.3237282526582,
            "y": -98.88679380587871
          },
          "label": "isValid",
          "nodeKind": "is-valid"
        },
        {
          "id": "node-get-journal-mqm98hvn-18",
          "blockKind": "custom",
          "position": {
            "x": 459.8034769485792,
            "y": 13.111038385640448
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        },
        {
          "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "blockKind": "custom",
          "position": {
            "x": 739.5364266894157,
            "y": -81.43640966577944
          },
          "label": "journal1",
          "nodeKind": "variable-set",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        }
      ],
      "edges": [
        {
          "source": "on-connect-event",
          "sourceHandle": "exec-out",
          "target": "node-is-valid-mqm97w5v-17",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "on-connect-event",
          "sourceHandle": "server",
          "target": "node-is-valid-mqm97w5v-17",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "ServerRef"
        },
        {
          "source": "on-connect-event",
          "sourceHandle": "server",
          "target": "node-get-journal-mqm98hvn-18",
          "targetHandle": "server",
          "kind": "data",
          "dataType": "ServerRef"
        },
        {
          "source": "node-is-valid-mqm97w5v-17",
          "sourceHandle": "exec-true-out",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-journal-mqm98hvn-18",
          "sourceHandle": "journal",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        }
      ]
    },
    "loops": {
      "main": {
        "entry": "main-on-tick",
        "nodes": [
          {
            "id": "main-on-tick",
            "blockKind": "custom",
            "position": {
              "x": -700.3126018437592,
              "y": -281.494470006514
            },
            "label": "onTick",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "loopTick"
          },
          {
            "id": "main-infinity",
            "blockKind": "custom",
            "position": {
              "x": 5128.052417513904,
              "y": 1056.2543504228324
            },
            "label": "∞",
            "nodeKind": "loop-repeat",
            "system": true
          },
          {
            "id": "node-is-valid-mql3c77w-6",
            "blockKind": "custom",
            "position": {
              "x": -375.3186574399972,
              "y": -107.01584256505302
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-get-audio-stream-mql3ckno-7",
            "blockKind": "custom",
            "position": {
              "x": -106.52472747074003,
              "y": -2.1324968378683664
            },
            "label": "GetAudioStream",
            "nodeKind": "get-audio-stream"
          },
          {
            "id": "node-get-sample-mql3f1ro-9",
            "blockKind": "custom",
            "position": {
              "x": 1041.4480185865475,
              "y": 197.81839440933837
            },
            "label": "GetSample",
            "nodeKind": "get-sample"
          },
          {
            "id": "node-get-fft-frame-mql3g2ys-11",
            "blockKind": "custom",
            "position": {
              "x": 1758.6491191717096,
              "y": 421.9223316578707
            },
            "label": "GetFFTFrame",
            "nodeKind": "get-fft-frame"
          },
          {
            "id": "node-device-global-mqm0q2fd-14",
            "blockKind": "custom",
            "position": {
              "x": 222.44273871657708,
              "y": -392.13257827383524
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-stop-runtime-mqm1mfts-29",
            "blockKind": "custom",
            "position": {
              "x": 511.90025358061894,
              "y": -322.4211147385492
            },
            "label": "StopRuntime",
            "nodeKind": "stop-runtime"
          },
          {
            "id": "node-is-valid-mqm1nky7-30",
            "blockKind": "custom",
            "position": {
              "x": 183.38127056229985,
              "y": -135.09097892214334
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-get-recorder-mqm9sdoi-25",
            "blockKind": "custom",
            "position": {
              "x": 1315.6043085466104,
              "y": 343.0295814824033
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          },
          {
            "id": "node-get-spectral-analyser-mqm9vz6a-27",
            "blockKind": "custom",
            "position": {
              "x": 2054.3842630108056,
              "y": 561.874564766818
            },
            "label": "GetSpectralAnalyser",
            "nodeKind": "get-spectral-analyser"
          },
          {
            "id": "node-collect-fft-frames-mqm9wezu-28",
            "blockKind": "custom",
            "position": {
              "x": 2287.07395578655,
              "y": 705.3218234856145
            },
            "label": "CollectFftFrames",
            "nodeKind": "collect-fft-frames",
            "collectorConfig": {
              "bufferSize": 2048,
              "smoothingTimeConstant": 0.75,
              "windowSec": 15,
              "queueCapacity": 999
            }
          },
          {
            "id": "node-get-reporter-mqm9yfmy-29",
            "blockKind": "custom",
            "position": {
              "x": 3169.748710684103,
              "y": 505.8391726709191
            },
            "label": "GetReporter",
            "nodeKind": "get-reporter"
          },
          {
            "id": "node-make-report-from-analysis-mqma356z-34",
            "blockKind": "custom",
            "position": {
              "x": 4287.30385238366,
              "y": 497.9052504486386
            },
            "label": "MakeReportFromAnalysis",
            "nodeKind": "make-report-from-analysis"
          },
          {
            "id": "node-publish-report-mqma49xv-35",
            "blockKind": "custom",
            "position": {
              "x": 4651.323099101254,
              "y": 388.4089045323267
            },
            "label": "PublishReport",
            "nodeKind": "publish-report"
          },
          {
            "id": "node-make-track-mqmcipn5-28",
            "blockKind": "custom",
            "position": {
              "x": 3556.6926855916026,
              "y": 338.85315683106893
            },
            "label": "MakeTrack",
            "nodeKind": "make-track"
          },
          {
            "id": "node-get-recorder-mqmo3mba-31",
            "blockKind": "custom",
            "position": {
              "x": 2566.53645968242,
              "y": 915.3490736945035
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          },
          {
            "id": "node-is-recording-window-full-mqmo40ie-32",
            "blockKind": "custom",
            "position": {
              "x": 2845.518227594041,
              "y": 792.6161982504036
            },
            "label": "IsRecordingWindowFull",
            "nodeKind": "is-recording-window-full"
          },
          {
            "id": "node-make-fft-trends-analysis-mqmo96xz-33",
            "blockKind": "custom",
            "position": {
              "x": 3940.8586932247003,
              "y": 662.9347369807047
            },
            "label": "MakeFftTrendsAnalysis",
            "nodeKind": "make-fft-trends-analysis"
          },
          {
            "id": "node-flush-spectral-analyser-mqmoa8o7-34",
            "blockKind": "custom",
            "position": {
              "x": 3850.9048086588978,
              "y": 754.0483991582826
            },
            "label": "FlushSpectralAnalyser",
            "nodeKind": "flush-spectral-analyser"
          },
          {
            "id": "node-stop-recording-mqmod4yf-35",
            "blockKind": "custom",
            "position": {
              "x": 3177.2615336697704,
              "y": 933.905285532332
            },
            "label": "StopRecording",
            "nodeKind": "stop-recording"
          },
          {
            "id": "node-start-recording-mqv07-36",
            "blockKind": "custom",
            "position": {
              "x": 3720.6926855916026,
              "y": 420.85315683106893
            },
            "label": "StartRecording (restart)",
            "nodeKind": "start-recording"
          },
          {
            "id": "node-start-recording-bootstrap-v08-2",
            "blockKind": "custom",
            "position": {
              "x": 3020.6926855916026,
              "y": 792.6161982504036
            },
            "label": "StartRecording (bootstrap)",
            "nodeKind": "start-recording",
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "node-make-recording-policy-v08-1",
            "blockKind": "custom",
            "position": {
              "x": 3580.6926855916026,
              "y": 420.85315683106893
            },
            "label": "MakeRecordingPolicy",
            "nodeKind": "make-recording-policy",
            "pure": true,
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "node-make-fft-trends-policy-v08-1",
            "blockKind": "custom",
            "position": {
              "x": 3780.6926855916026,
              "y": 580.8531568310689
            },
            "label": "MakeFftTrendsPolicy",
            "nodeKind": "make-fft-trends-policy",
            "pure": true,
            "fftTrendsPolicy": {
              "detectionMode": "auto",
              "measurementsCount": 20,
              "intervalMs": 500,
              "minConfidence": 0.55,
              "minRms": 0.02,
              "enabledTemplateKeys": [
                "DRONE_TIGHT",
                "WIND",
                "QUIET",
                "TRAFFIC",
                "BIRDS",
                "VOICE"
              ]
            }
          },
          {
            "id": "node-get-microphone-mvp-main-1",
            "blockKind": "custom",
            "position": {
              "x": -708,
              "y": 29
            },
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
          },
          {
            "id": "node-get-journal-mvp-main-1",
            "blockKind": "custom",
            "position": {
              "x": 2434,
              "y": 120
            },
            "label": "GetJournal",
            "nodeKind": "get-journal"
          }
        ],
        "edges": [
          {
            "source": "main-on-tick",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mql3c77w-6",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-valid-mql3c77w-6",
            "sourceHandle": "exec-true-out",
            "target": "node-get-audio-stream-mql3ckno-7",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-sample-mql3f1ro-9",
            "sourceHandle": "sample",
            "target": "node-get-fft-frame-mql3g2ys-11",
            "targetHandle": "sample",
            "kind": "data",
            "dataType": "AudioSampleRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-is-valid-mql3c77w-6",
            "sourceHandle": "exec-false-out",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mqm1nky7-30",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-is-valid-mqm1nky7-30",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-is-valid-mqm1nky7-30",
            "sourceHandle": "exec-false-out",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-sample-mql3f1ro-9",
            "sourceHandle": "exec-out",
            "target": "node-get-recorder-mqm9sdoi-25",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "exec-out",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-fft-frame-mql3g2ys-11",
            "sourceHandle": "exec-out",
            "target": "node-get-spectral-analyser-mqm9vz6a-27",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "exec-out",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "report",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "report",
            "kind": "data",
            "dataType": "ReportRef"
          },
          {
            "source": "node-get-reporter-mqm9yfmy-29",
            "sourceHandle": "reporter",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "node-get-fft-frame-mql3g2ys-11",
            "sourceHandle": "frame",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "frame",
            "kind": "data",
            "dataType": "FftFrameRef"
          },
          {
            "source": "node-get-recorder-mqm9sdoi-25",
            "sourceHandle": "recorder",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-get-recorder-mqm9sdoi-25",
            "sourceHandle": "exec-out",
            "target": "node-get-fft-frame-mql3g2ys-11",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-collect-fft-frames-mqm9wezu-28",
            "sourceHandle": "exec-out",
            "target": "node-get-recorder-mqmo3mba-31",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-false-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-flush-spectral-analyser-mqmoa8o7-34",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-start-recording-mqv07-36",
            "sourceHandle": "exec-out",
            "target": "node-flush-spectral-analyser-mqmoa8o7-34",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-flush-spectral-analyser-mqmoa8o7-34",
            "sourceHandle": "exec-out",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-flush-spectral-analyser-mqmoa8o7-34",
            "sourceHandle": "frames",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "frames",
            "kind": "data",
            "dataType": "FftFrameRefList"
          },
          {
            "source": "node-make-fft-trends-analysis-mqmo96xz-33",
            "sourceHandle": "exec-out",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-fft-trends-analysis-mqmo96xz-33",
            "sourceHandle": "analysis",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "analysis",
            "kind": "data",
            "dataType": "FftTrendAnalysisRef"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "exec-out",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-start-recording-bootstrap-v08-2",
            "sourceHandle": "exec-out",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-make-recording-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "RecordingPolicy"
          },
          {
            "source": "node-make-fft-trends-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "FftTrendsPolicy"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-true-out",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "exec-out",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "slice",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "slice",
            "kind": "data",
            "dataType": "RecordingSliceRef"
          },
          {
            "source": "node-publish-report-mqma49xv-35",
            "sourceHandle": "exec-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-track-mqmcipn5-28",
            "sourceHandle": "exec-out",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-recording-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "RecordingPolicy"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-microphone-mvp-main-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-microphone-mvp-main-1",
            "sourceHandle": "microphone",
            "target": "node-is-valid-mql3c77w-6",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "MicrophoneRef"
          },
          {
            "source": "node-get-microphone-mvp-main-1",
            "sourceHandle": "microphone",
            "target": "node-get-audio-stream-mql3ckno-7",
            "targetHandle": "microphone",
            "kind": "data",
            "dataType": "MicrophoneRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-journal-mvp-main-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-journal-mvp-main-1",
            "sourceHandle": "journal",
            "target": "node-get-reporter-mqm9yfmy-29",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-get-journal-mvp-main-1",
            "sourceHandle": "journal",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqm9sdoi-25",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-spectral-analyser-mqm9vz6a-27",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqmo3mba-31",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-is-valid-mqm1nky7-30",
            "sourceHandle": "exec-true-out",
            "target": "node-get-sample-mql3f1ro-9",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-get-sample-mql3f1ro-9",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          }
        ]
      },
      "alarm": {
        "entry": "alarm-on-tick",
        "nodes": [
          {
            "id": "alarm-on-tick",
            "blockKind": "custom",
            "position": {
              "x": 40,
              "y": 180
            },
            "label": "onTick",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "loopTick"
          },
          {
            "id": "alarm-infinity",
            "blockKind": "custom",
            "position": {
              "x": 360,
              "y": 180
            },
            "label": "∞",
            "nodeKind": "loop-repeat",
            "system": true
          }
        ],
        "edges": [
          {
            "source": "alarm-on-tick",
            "sourceHandle": "exec-out",
            "target": "alarm-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          }
        ]
      }
    },
    "triggers": {
      "onStop": {
        "entry": "on-stop-event",
        "nodes": [
          {
            "id": "on-stop-event",
            "blockKind": "custom",
            "position": {
              "x": 101.3403087605697,
              "y": 49.02423358410924
            },
            "label": "On stop",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "handler"
          },
          {
            "id": "node-is-valid-mqm9nw3u-21",
            "blockKind": "custom",
            "position": {
              "x": 380.7712084304274,
              "y": 102.59718353023794
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-stop-streaming-mqm9ofcy-22",
            "blockKind": "custom",
            "position": {
              "x": 669.9804427166014,
              "y": 164.3341571764124
            },
            "label": "StopStreaming",
            "nodeKind": "stop-streaming"
          },
          {
            "id": "node-device-global-mvp-onstop-1",
            "blockKind": "custom",
            "position": {
              "x": -120,
              "y": 180
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-get-microphone-mvp-onstop-1",
            "blockKind": "custom",
            "position": {
              "x": 54,
              "y": 249
            },
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
          }
        ],
        "edges": [
          {
            "source": "on-stop-event",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mqm9nw3u-21",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-valid-mqm9nw3u-21",
            "sourceHandle": "exec-true-out",
            "target": "node-stop-streaming-mqm9ofcy-22",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-device-global-mvp-onstop-1",
            "sourceHandle": "device",
            "target": "node-get-microphone-mvp-onstop-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          }
        ]
      },
      "onDisconnect": {
        "entry": "on-disconnect-event",
        "nodes": [
          {
            "id": "on-disconnect-event",
            "blockKind": "custom",
            "position": {
              "x": -97.59667536385254,
              "y": -130.99663096911144
            },
            "label": "On disconnect",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "handler"
          },
          {
            "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "blockKind": "custom",
            "position": {
              "x": 459.82659586001006,
              "y": -33.84148936113069
            },
            "label": "journal1",
            "nodeKind": "variable-set",
            "variableId": "var-JournalRef-mqm9dl4a-6"
          },
          {
            "id": "node-device-global-mqm9pz9v-23",
            "blockKind": "custom",
            "position": {
              "x": -102.30174820635386,
              "y": 86.1361013669701
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-get-journal-mqm9q43m-24",
            "blockKind": "custom",
            "position": {
              "x": 186.67135917857937,
              "y": 5.184030612241209
            },
            "label": "GetJournal",
            "nodeKind": "get-journal"
          }
        ],
        "edges": [
          {
            "source": "node-device-global-mqm9pz9v-23",
            "sourceHandle": "device",
            "target": "node-get-journal-mqm9q43m-24",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "on-disconnect-event",
            "sourceHandle": "exec-out",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-journal-mqm9q43m-24",
            "sourceHandle": "journal",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "JournalRef"
          }
        ]
      },
      "custom": []
    },
    "functions": [],
    "scheduled": [],
    "variables": [
      {
        "id": "var-JournalRef-mqm9dl4a-6",
        "name": "journal1",
        "type": "JournalRef",
        "value": null
      }
    ]
  }
} as unknown as DeviceScenarioDocument;
