/**
 * AUTO-GENERATED by yarn usercase:build — do not edit.
 */
import type { DeviceScenarioDocument } from '@membrana/core';

export const DEFAULT_USERCASE_MVP_MICROPHONE_DOCUMENT = {
  "version": 2,
  "kind": "device-scenario",
  "deviceKind": "microphone",
  "meta": {
    "title": "UserCase MVP microphone (default)",
    "exportedAt": "2026-06-21T13:08:46.264Z"
  },
  "signalGraph": {
    "nodes": [],
    "edges": []
  },
  "scenario": {
    "initial": {
      "entry": "initial-event",
      "nodes": [
        {
          "id": "initial-event",
          "blockKind": "custom",
          "position": {
            "x": -1888,
            "y": -600
          },
          "label": "On start",
          "nodeKind": "event",
          "system": true,
          "eventVariant": "handler"
        },
        {
          "id": "node-get-microphone-mqkpxb3c-5",
          "blockKind": "custom",
          "position": {
            "x": -32,
            "y": -600
          },
          "label": "GetMicrophone",
          "nodeKind": "get-microphone",
          "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
        },
        {
          "id": "node-print-mqksbm4o-3",
          "blockKind": "custom",
          "position": {
            "x": -496,
            "y": -600
          },
          "label": "Print",
          "nodeKind": "print"
        },
        {
          "id": "node-start-streaming-mql556hh-49",
          "blockKind": "custom",
          "position": {
            "x": 432,
            "y": -600
          },
          "label": "StartStreaming",
          "nodeKind": "start-streaming"
        },
        {
          "id": "node-is-valid-mqm9i48b-18",
          "blockKind": "custom",
          "position": {
            "x": -1424,
            "y": -600
          },
          "label": "isValid",
          "nodeKind": "is-valid"
        },
        {
          "id": "node-device-global-mqm9ip17-19",
          "blockKind": "custom",
          "position": {
            "x": -1760,
            "y": -80
          },
          "label": "GetDevice",
          "nodeKind": "device-global"
        },
        {
          "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "blockKind": "custom",
          "position": {
            "x": -960,
            "y": -560
          },
          "label": "journal1",
          "nodeKind": "variable-set",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        },
        {
          "id": "node-get-journal-mqm9j4wy-20",
          "blockKind": "custom",
          "position": {
            "x": -1064,
            "y": -248
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        },
        {
          "id": "node-get-journal-mvp-initial-valid-1",
          "blockKind": "custom",
          "position": {
            "x": -1752,
            "y": -240
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        }
      ],
      "edges": [
        {
          "source": "initial-event",
          "sourceHandle": "exec-out",
          "target": "node-is-valid-mqm9i48b-18",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-device-global-mqm9ip17-19",
          "sourceHandle": "device",
          "target": "node-get-journal-mqm9j4wy-20",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-is-valid-mqm9i48b-18",
          "sourceHandle": "exec-false-out",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-journal-mqm9j4wy-20",
          "sourceHandle": "journal",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        },
        {
          "source": "node-device-global-mqm9ip17-19",
          "sourceHandle": "device",
          "target": "node-get-journal-mvp-initial-valid-1",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-get-journal-mvp-initial-valid-1",
          "sourceHandle": "journal",
          "target": "node-is-valid-mqm9i48b-18",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        },
        {
          "source": "initial-event",
          "sourceHandle": "device",
          "target": "node-get-microphone-mqkpxb3c-5",
          "targetHandle": "device",
          "kind": "data",
          "dataType": "DeviceRef"
        },
        {
          "source": "node-get-microphone-mqkpxb3c-5",
          "sourceHandle": "microphone",
          "target": "node-start-streaming-mql556hh-49",
          "targetHandle": "microphone",
          "kind": "data",
          "dataType": "MicrophoneRef"
        },
        {
          "source": "initial-event",
          "sourceHandle": "datetime",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "DateTime"
        },
        {
          "source": "node-is-valid-mqm9i48b-18",
          "sourceHandle": "exec-true-out",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-print-mqksbm4o-3",
          "sourceHandle": "exec-out",
          "target": "node-get-microphone-mqkpxb3c-5",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-microphone-mqkpxb3c-5",
          "sourceHandle": "exec-out",
          "target": "node-start-streaming-mql556hh-49",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9it3v-10",
          "sourceHandle": "exec-out",
          "target": "node-print-mqksbm4o-3",
          "targetHandle": "exec-in",
          "kind": "exec"
        }
      ]
    },
    "onConnect": {
      "entry": "on-connect-event",
      "nodes": [
        {
          "id": "on-connect-event",
          "blockKind": "custom",
          "position": {
            "x": -144,
            "y": -96
          },
          "label": "On connect",
          "nodeKind": "event",
          "system": true,
          "eventVariant": "handler"
        },
        {
          "id": "node-is-valid-mqm97w5v-17",
          "blockKind": "custom",
          "position": {
            "x": 320,
            "y": -96
          },
          "label": "isValid",
          "nodeKind": "is-valid"
        },
        {
          "id": "node-get-journal-mqm98hvn-18",
          "blockKind": "custom",
          "position": {
            "x": 456,
            "y": 16
          },
          "label": "GetJournal",
          "nodeKind": "get-journal"
        },
        {
          "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "blockKind": "custom",
          "position": {
            "x": 784,
            "y": -96
          },
          "label": "journal1",
          "nodeKind": "variable-set",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        }
      ],
      "edges": [
        {
          "source": "on-connect-event",
          "sourceHandle": "exec-out",
          "target": "node-is-valid-mqm97w5v-17",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "on-connect-event",
          "sourceHandle": "server",
          "target": "node-is-valid-mqm97w5v-17",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "ServerRef"
        },
        {
          "source": "on-connect-event",
          "sourceHandle": "server",
          "target": "node-get-journal-mqm98hvn-18",
          "targetHandle": "server",
          "kind": "data",
          "dataType": "ServerRef"
        },
        {
          "source": "node-is-valid-mqm97w5v-17",
          "sourceHandle": "exec-true-out",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "targetHandle": "exec-in",
          "kind": "exec"
        },
        {
          "source": "node-get-journal-mqm98hvn-18",
          "sourceHandle": "journal",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "targetHandle": "value",
          "kind": "data",
          "dataType": "JournalRef"
        }
      ]
    },
    "loops": {
      "main": {
        "entry": "main-on-tick",
        "nodes": [
          {
            "id": "main-on-tick",
            "blockKind": "custom",
            "position": {
              "x": -704,
              "y": -224
            },
            "label": "onTick",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "loopTick"
          },
          {
            "id": "main-infinity",
            "blockKind": "custom",
            "position": {
              "x": 8112,
              "y": -280
            },
            "label": "∞",
            "nodeKind": "loop-repeat",
            "system": true
          },
          {
            "id": "node-is-valid-mql3c77w-6",
            "blockKind": "custom",
            "position": {
              "x": -240,
              "y": -224
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-get-audio-stream-mql3ckno-7",
            "blockKind": "custom",
            "position": {
              "x": 224,
              "y": -272
            },
            "label": "GetAudioStream",
            "nodeKind": "get-audio-stream"
          },
          {
            "id": "node-get-sample-mql3f1ro-9",
            "blockKind": "custom",
            "position": {
              "x": 1152,
              "y": -280
            },
            "label": "GetSample",
            "nodeKind": "get-sample"
          },
          {
            "id": "node-get-fft-frame-mql3g2ys-11",
            "blockKind": "custom",
            "position": {
              "x": 2080,
              "y": -280
            },
            "label": "GetFFTFrame",
            "nodeKind": "get-fft-frame"
          },
          {
            "id": "node-device-global-mqm0q2fd-14",
            "blockKind": "custom",
            "position": {
              "x": 224,
              "y": -392
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-stop-runtime-mqm1mfts-29",
            "blockKind": "custom",
            "position": {
              "x": 1152,
              "y": -160
            },
            "label": "StopRuntime",
            "nodeKind": "stop-runtime"
          },
          {
            "id": "node-is-valid-mqm1nky7-30",
            "blockKind": "custom",
            "position": {
              "x": 688,
              "y": -272
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-get-recorder-mqm9sdoi-25",
            "blockKind": "custom",
            "position": {
              "x": 1616,
              "y": -280
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          },
          {
            "id": "node-get-spectral-analyser-mqm9vz6a-27",
            "blockKind": "custom",
            "position": {
              "x": 2544,
              "y": -280
            },
            "label": "GetSpectralAnalyser",
            "nodeKind": "get-spectral-analyser"
          },
          {
            "id": "node-collect-fft-frames-mqm9wezu-28",
            "blockKind": "custom",
            "position": {
              "x": 3008,
              "y": -280
            },
            "label": "CollectFftFrames",
            "nodeKind": "collect-fft-frames",
            "collectorConfig": {
              "bufferSize": 2048,
              "smoothingTimeConstant": 0.75,
              "windowSec": 15,
              "queueCapacity": 999
            }
          },
          {
            "id": "node-get-reporter-mqm9yfmy-29",
            "blockKind": "custom",
            "position": {
              "x": 3168,
              "y": 504
            },
            "label": "GetReporter",
            "nodeKind": "get-reporter"
          },
          {
            "id": "node-make-report-from-analysis-mqma356z-34",
            "blockKind": "custom",
            "position": {
              "x": 7184,
              "y": -320
            },
            "label": "MakeReportFromAnalysis",
            "nodeKind": "make-report-from-analysis"
          },
          {
            "id": "node-publish-report-mqma49xv-35",
            "blockKind": "custom",
            "position": {
              "x": 7648,
              "y": -320
            },
            "label": "PublishReport",
            "nodeKind": "publish-report"
          },
          {
            "id": "node-make-track-mqmcipn5-28",
            "blockKind": "custom",
            "position": {
              "x": 5328,
              "y": -320
            },
            "label": "MakeTrack",
            "nodeKind": "make-track"
          },
          {
            "id": "node-get-recorder-mqmo3mba-31",
            "blockKind": "custom",
            "position": {
              "x": 3472,
              "y": -280
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          },
          {
            "id": "node-is-recording-window-full-mqmo40ie-32",
            "blockKind": "custom",
            "position": {
              "x": 4400,
              "y": -280
            },
            "label": "IsRecordingWindowFull",
            "nodeKind": "is-recording-window-full"
          },
          {
            "id": "node-make-fft-trends-analysis-mqmo96xz-33",
            "blockKind": "custom",
            "position": {
              "x": 6720,
              "y": -320
            },
            "label": "MakeFftTrendsAnalysis",
            "nodeKind": "make-fft-trends-analysis"
          },
          {
            "id": "node-flush-spectral-analyser-mqmoa8o7-34",
            "blockKind": "custom",
            "position": {
              "x": 6256,
              "y": -320
            },
            "label": "FlushSpectralAnalyser",
            "nodeKind": "flush-spectral-analyser"
          },
          {
            "id": "node-stop-recording-mqmod4yf-35",
            "blockKind": "custom",
            "position": {
              "x": 4864,
              "y": -320
            },
            "label": "StopRecording",
            "nodeKind": "stop-recording"
          },
          {
            "id": "node-start-recording-mqv07-36",
            "blockKind": "custom",
            "position": {
              "x": 5792,
              "y": -320
            },
            "label": "StartRecording (restart)",
            "nodeKind": "start-recording"
          },
          {
            "id": "node-start-recording-bootstrap-v08-2",
            "blockKind": "custom",
            "position": {
              "x": 3936,
              "y": -280
            },
            "label": "StartRecording (bootstrap)",
            "nodeKind": "start-recording",
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "node-make-recording-policy-v08-1",
            "blockKind": "custom",
            "position": {
              "x": 3584,
              "y": 424
            },
            "label": "MakeRecordingPolicy",
            "nodeKind": "make-recording-policy",
            "pure": true,
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "node-make-fft-trends-policy-v08-1",
            "blockKind": "custom",
            "position": {
              "x": 3784,
              "y": 584
            },
            "label": "MakeFftTrendsPolicy",
            "nodeKind": "make-fft-trends-policy",
            "pure": true,
            "fftTrendsPolicy": {
              "detectionMode": "auto",
              "measurementsCount": 20,
              "intervalMs": 500,
              "minConfidence": 0.55,
              "minRms": 0.02,
              "enabledTemplateKeys": [
                "DRONE_TIGHT",
                "WIND",
                "QUIET",
                "TRAFFIC",
                "BIRDS",
                "VOICE"
              ]
            }
          },
          {
            "id": "node-get-microphone-mvp-main-1",
            "blockKind": "custom",
            "position": {
              "x": -704,
              "y": 32
            },
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
          },
          {
            "id": "node-get-journal-mvp-main-1",
            "blockKind": "custom",
            "position": {
              "x": 2432,
              "y": 120
            },
            "label": "GetJournal",
            "nodeKind": "get-journal"
          }
        ],
        "edges": [
          {
            "source": "main-on-tick",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mql3c77w-6",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-valid-mql3c77w-6",
            "sourceHandle": "exec-true-out",
            "target": "node-get-audio-stream-mql3ckno-7",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-sample-mql3f1ro-9",
            "sourceHandle": "sample",
            "target": "node-get-fft-frame-mql3g2ys-11",
            "targetHandle": "sample",
            "kind": "data",
            "dataType": "AudioSampleRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-is-valid-mql3c77w-6",
            "sourceHandle": "exec-false-out",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mqm1nky7-30",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-is-valid-mqm1nky7-30",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-is-valid-mqm1nky7-30",
            "sourceHandle": "exec-false-out",
            "target": "node-stop-runtime-mqm1mfts-29",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-sample-mql3f1ro-9",
            "sourceHandle": "exec-out",
            "target": "node-get-recorder-mqm9sdoi-25",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "exec-out",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-fft-frame-mql3g2ys-11",
            "sourceHandle": "exec-out",
            "target": "node-get-spectral-analyser-mqm9vz6a-27",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "exec-out",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "report",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "report",
            "kind": "data",
            "dataType": "ReportRef"
          },
          {
            "source": "node-get-reporter-mqm9yfmy-29",
            "sourceHandle": "reporter",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "node-get-fft-frame-mql3g2ys-11",
            "sourceHandle": "frame",
            "target": "node-collect-fft-frames-mqm9wezu-28",
            "targetHandle": "frame",
            "kind": "data",
            "dataType": "FftFrameRef"
          },
          {
            "source": "node-get-recorder-mqm9sdoi-25",
            "sourceHandle": "recorder",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-get-recorder-mqm9sdoi-25",
            "sourceHandle": "exec-out",
            "target": "node-get-fft-frame-mql3g2ys-11",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-collect-fft-frames-mqm9wezu-28",
            "sourceHandle": "exec-out",
            "target": "node-get-recorder-mqmo3mba-31",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-false-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-get-spectral-analyser-mqm9vz6a-27",
            "sourceHandle": "analyser",
            "target": "node-flush-spectral-analyser-mqmoa8o7-34",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-start-recording-mqv07-36",
            "sourceHandle": "exec-out",
            "target": "node-flush-spectral-analyser-mqmoa8o7-34",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-flush-spectral-analyser-mqmoa8o7-34",
            "sourceHandle": "exec-out",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-flush-spectral-analyser-mqmoa8o7-34",
            "sourceHandle": "frames",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "frames",
            "kind": "data",
            "dataType": "FftFrameRefList"
          },
          {
            "source": "node-make-fft-trends-analysis-mqmo96xz-33",
            "sourceHandle": "exec-out",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-fft-trends-analysis-mqmo96xz-33",
            "sourceHandle": "analysis",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "analysis",
            "kind": "data",
            "dataType": "FftTrendAnalysisRef"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "exec-out",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-start-recording-bootstrap-v08-2",
            "sourceHandle": "exec-out",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-make-recording-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "RecordingPolicy"
          },
          {
            "source": "node-make-fft-trends-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-make-fft-trends-analysis-mqmo96xz-33",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "FftTrendsPolicy"
          },
          {
            "source": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "recorder",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-true-out",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "exec-out",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "slice",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "slice",
            "kind": "data",
            "dataType": "RecordingSliceRef"
          },
          {
            "source": "node-publish-report-mqma49xv-35",
            "sourceHandle": "exec-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-track-mqmcipn5-28",
            "sourceHandle": "exec-out",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-recording-policy-v08-1",
            "sourceHandle": "policy",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "RecordingPolicy"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-microphone-mvp-main-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-microphone-mvp-main-1",
            "sourceHandle": "microphone",
            "target": "node-is-valid-mql3c77w-6",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "MicrophoneRef"
          },
          {
            "source": "node-get-microphone-mvp-main-1",
            "sourceHandle": "microphone",
            "target": "node-get-audio-stream-mql3ckno-7",
            "targetHandle": "microphone",
            "kind": "data",
            "dataType": "MicrophoneRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-journal-mvp-main-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-journal-mvp-main-1",
            "sourceHandle": "journal",
            "target": "node-get-reporter-mqm9yfmy-29",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-get-journal-mvp-main-1",
            "sourceHandle": "journal",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqm9sdoi-25",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-spectral-analyser-mqm9vz6a-27",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqmo3mba-31",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-is-valid-mqm1nky7-30",
            "sourceHandle": "exec-true-out",
            "target": "node-get-sample-mql3f1ro-9",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-get-sample-mql3f1ro-9",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-start-recording-mqv07-36",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-get-audio-stream-mql3ckno-7",
            "sourceHandle": "stream",
            "target": "node-start-recording-bootstrap-v08-2",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          }
        ]
      },
      "alarm": {
        "entry": "alarm-on-tick",
        "nodes": [
          {
            "id": "alarm-on-tick",
            "blockKind": "custom",
            "position": {
              "x": 40,
              "y": 184
            },
            "label": "onTick",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "loopTick"
          },
          {
            "id": "alarm-infinity",
            "blockKind": "custom",
            "position": {
              "x": 504,
              "y": 184
            },
            "label": "∞",
            "nodeKind": "loop-repeat",
            "system": true
          }
        ],
        "edges": [
          {
            "source": "alarm-on-tick",
            "sourceHandle": "exec-out",
            "target": "alarm-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          }
        ]
      }
    },
    "triggers": {
      "onStop": {
        "entry": "on-stop-event",
        "nodes": [
          {
            "id": "on-stop-event",
            "blockKind": "custom",
            "position": {
              "x": 104,
              "y": 48
            },
            "label": "On stop",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "handler"
          },
          {
            "id": "node-is-valid-mqm9nw3u-21",
            "blockKind": "custom",
            "position": {
              "x": 568,
              "y": 48
            },
            "label": "isValid",
            "nodeKind": "is-valid"
          },
          {
            "id": "node-stop-streaming-mqm9ofcy-22",
            "blockKind": "custom",
            "position": {
              "x": 1032,
              "y": 48
            },
            "label": "StopStreaming",
            "nodeKind": "stop-streaming"
          },
          {
            "id": "node-device-global-mvp-onstop-1",
            "blockKind": "custom",
            "position": {
              "x": -120,
              "y": 184
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-get-microphone-mvp-onstop-1",
            "blockKind": "custom",
            "position": {
              "x": 56,
              "y": 312
            },
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
          }
        ],
        "edges": [
          {
            "source": "on-stop-event",
            "sourceHandle": "exec-out",
            "target": "node-is-valid-mqm9nw3u-21",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-valid-mqm9nw3u-21",
            "sourceHandle": "exec-true-out",
            "target": "node-stop-streaming-mqm9ofcy-22",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-device-global-mvp-onstop-1",
            "sourceHandle": "device",
            "target": "node-get-microphone-mvp-onstop-1",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          }
        ]
      },
      "onDisconnect": {
        "entry": "on-disconnect-event",
        "nodes": [
          {
            "id": "on-disconnect-event",
            "blockKind": "custom",
            "position": {
              "x": -96,
              "y": -128
            },
            "label": "On disconnect",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "handler"
          },
          {
            "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "blockKind": "custom",
            "position": {
              "x": 368,
              "y": -128
            },
            "label": "journal1",
            "nodeKind": "variable-set",
            "variableId": "var-JournalRef-mqm9dl4a-6"
          },
          {
            "id": "node-device-global-mqm9pz9v-23",
            "blockKind": "custom",
            "position": {
              "x": -104,
              "y": 88
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-get-journal-mqm9q43m-24",
            "blockKind": "custom",
            "position": {
              "x": 184,
              "y": 8
            },
            "label": "GetJournal",
            "nodeKind": "get-journal"
          }
        ],
        "edges": [
          {
            "source": "node-device-global-mqm9pz9v-23",
            "sourceHandle": "device",
            "target": "node-get-journal-mqm9q43m-24",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "on-disconnect-event",
            "sourceHandle": "exec-out",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-journal-mqm9q43m-24",
            "sourceHandle": "journal",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "targetHandle": "value",
            "kind": "data",
            "dataType": "JournalRef"
          }
        ]
      },
      "custom": []
    },
    "functions": [],
    "scheduled": [],
    "variables": [
      {
        "id": "var-JournalRef-mqm9dl4a-6",
        "name": "journal1",
        "type": "JournalRef",
        "value": null
      }
    ],
    "commentGroups": [
      {
        "id": "ucg-main-policy",
        "branch": "main",
        "title": "Policy constructors",
        "description": "MakeRecordingPolicy и MakeFftTrendsPolicy",
        "frameColor": {
          "preset": "primary"
        },
        "rect": {
          "x": 3560,
          "y": 400,
          "width": 472,
          "height": 312
        },
        "nodeIds": [
          "node-make-recording-policy-v08-1",
          "node-make-fft-trends-policy-v08-1"
        ]
      },
      {
        "id": "ucg-main-recording-gate",
        "branch": "main",
        "title": "Recording gate",
        "description": "Start/stop recording, window gate, MakeTrack",
        "frameColor": {
          "preset": "warning"
        },
        "rect": {
          "x": 1592,
          "y": -344,
          "width": 4448,
          "height": 192
        },
        "nodeIds": [
          "node-get-recorder-mqm9sdoi-25",
          "node-make-track-mqmcipn5-28",
          "node-get-recorder-mqmo3mba-31",
          "node-is-recording-window-full-mqmo40ie-32",
          "node-stop-recording-mqmod4yf-35",
          "node-start-recording-mqv07-36",
          "node-start-recording-bootstrap-v08-2"
        ]
      },
      {
        "id": "ucg-main-trends-fft",
        "branch": "main",
        "title": "Trends FFT",
        "description": "Spectral analyser, FFT frames, analysis",
        "frameColor": {
          "preset": "info"
        },
        "rect": {
          "x": 1128,
          "y": -344,
          "width": 5840,
          "height": 192
        },
        "nodeIds": [
          "node-get-sample-mql3f1ro-9",
          "node-get-fft-frame-mql3g2ys-11",
          "node-get-spectral-analyser-mqm9vz6a-27",
          "node-collect-fft-frames-mqm9wezu-28",
          "node-make-fft-trends-analysis-mqmo96xz-33",
          "node-flush-spectral-analyser-mqmoa8o7-34"
        ]
      },
      {
        "id": "ucg-main-journal",
        "branch": "main",
        "title": "Journal",
        "description": "Reporter, track report, publish",
        "frameColor": {
          "preset": "accent"
        },
        "rect": {
          "x": 2408,
          "y": -344,
          "width": 5488,
          "height": 976
        },
        "nodeIds": [
          "node-get-reporter-mqm9yfmy-29",
          "node-make-report-from-analysis-mqma356z-34",
          "node-publish-report-mqma49xv-35",
          "node-get-journal-mvp-main-1"
        ]
      }
    ]
  }
} as unknown as DeviceScenarioDocument;
