/**
 * AUTO-GENERATED by yarn usercase:build — do not edit.
 */
import type { DeviceScenarioDocument } from '@membrana/core';

export const DEFAULT_USERCASE_MVP_MICROPHONE_BETA_ASYNC_V2_DOCUMENT = {
  "version": 2,
  "kind": "device-scenario",
  "deviceKind": "microphone",
  "meta": {
    "title": "MVP microphone · Beta (Measured modular UserCase, async v2)",
    "exportedAt": "2026-06-25T16:07:40.121Z",
    "bundledGraphVersion": "v2.0-async",
    "commentGroupProfile": "beta",
    "isCompetitionTemplate": true,
    "executionPolicy": "competition",
    "competitionTimeoutSec": 600,
    "competitionBase": "v2.0-async"
  },
  "signalGraph": {
    "nodes": [
      {
        "id": "signal-capture",
        "pluginId": "microphone",
        "position": {
          "x": 80,
          "y": 140
        }
      },
      {
        "id": "signal-analyzer",
        "pluginId": "fft-analyzer",
        "position": {
          "x": 340,
          "y": 140
        }
      }
    ],
    "edges": [
      {
        "source": "signal-capture",
        "target": "signal-analyzer",
        "sourceHandle": "audio-out",
        "targetHandle": "audio-in"
      }
    ]
  },
  "scenario": {
    "initial": {
      "entry": "initial-event",
      "nodes": [
        {
          "id": "initial-event",
          "label": "On start",
          "system": true,
          "nodeKind": "event",
          "position": {
            "x": -1888,
            "y": -728
          },
          "blockKind": "custom",
          "eventVariant": "handler"
        },
        {
          "id": "node-get-microphone-mqkpxb3c-5",
          "label": "GetMicrophone",
          "nodeKind": "get-microphone",
          "position": {
            "x": -1424,
            "y": -728
          },
          "blockKind": "custom",
          "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
        },
        {
          "id": "node-start-streaming-mql556hh-49",
          "label": "StartStreaming",
          "nodeKind": "start-streaming",
          "position": {
            "x": -960,
            "y": -728
          },
          "blockKind": "custom"
        },
        {
          "id": "fn-1-block",
          "label": "StartRecording::fn-1",
          "position": {
            "x": -496,
            "y": -728
          },
          "blockKind": "subgraph"
        }
      ],
      "edges": [
        {
          "kind": "data",
          "source": "initial-event",
          "target": "node-get-microphone-mqkpxb3c-5",
          "dataType": "DeviceRef",
          "sourceHandle": "device",
          "targetHandle": "device"
        },
        {
          "kind": "data",
          "source": "node-get-microphone-mqkpxb3c-5",
          "target": "node-start-streaming-mql556hh-49",
          "dataType": "MicrophoneRef",
          "sourceHandle": "microphone",
          "targetHandle": "microphone"
        },
        {
          "kind": "exec",
          "source": "node-get-microphone-mqkpxb3c-5",
          "target": "node-start-streaming-mql556hh-49",
          "sourceHandle": "exec-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "exec",
          "source": "initial-event",
          "target": "node-get-microphone-mqkpxb3c-5",
          "sourceHandle": "exec-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "exec",
          "source": "node-start-streaming-mql556hh-49",
          "target": "fn-1-block",
          "sourceHandle": "exec-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "data",
          "source": "initial-event",
          "target": "fn-1-block",
          "dataType": "DeviceRef",
          "sourceHandle": "device",
          "targetHandle": "device"
        },
        {
          "kind": "data",
          "source": "node-start-streaming-mql556hh-49",
          "target": "fn-1-block",
          "dataType": "AudioStreamRef",
          "sourceHandle": "stream",
          "targetHandle": "stream"
        }
      ]
    },
    "onConnect": {
      "entry": "on-connect-event",
      "nodes": [
        {
          "id": "on-connect-event",
          "label": "On connect",
          "system": true,
          "nodeKind": "event",
          "position": {
            "x": -144,
            "y": -88
          },
          "blockKind": "custom",
          "eventVariant": "handler"
        },
        {
          "id": "node-is-valid-mqm97w5v-17",
          "label": "isValid",
          "nodeKind": "is-valid",
          "position": {
            "x": 320,
            "y": -88
          },
          "blockKind": "custom"
        },
        {
          "id": "node-get-journal-mqm98hvn-18",
          "label": "GetJournal",
          "nodeKind": "get-journal",
          "position": {
            "x": 288,
            "y": 168
          },
          "blockKind": "custom"
        },
        {
          "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "label": "journal1",
          "nodeKind": "variable-set",
          "position": {
            "x": 784,
            "y": -24
          },
          "blockKind": "custom",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        },
        {
          "id": "board-mqrk8res-sfp1k7n9",
          "label": "journal1",
          "nodeKind": "variable-set",
          "position": {
            "x": 784,
            "y": -152
          },
          "blockKind": "custom",
          "variableId": "var-JournalRef-mqm9dl4a-6"
        },
        {
          "id": "node-get-journal-mqrk8yrn-121",
          "label": "GetJournal",
          "nodeKind": "get-journal",
          "position": {
            "x": 288,
            "y": 40
          },
          "blockKind": "custom"
        }
      ],
      "edges": [
        {
          "kind": "exec",
          "source": "on-connect-event",
          "target": "node-is-valid-mqm97w5v-17",
          "sourceHandle": "exec-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "data",
          "source": "on-connect-event",
          "target": "node-is-valid-mqm97w5v-17",
          "dataType": "ServerRef",
          "sourceHandle": "server",
          "targetHandle": "value"
        },
        {
          "kind": "data",
          "source": "on-connect-event",
          "target": "node-get-journal-mqm98hvn-18",
          "dataType": "ServerRef",
          "sourceHandle": "server",
          "targetHandle": "server"
        },
        {
          "kind": "exec",
          "source": "node-is-valid-mqm97w5v-17",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "sourceHandle": "exec-true-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "data",
          "source": "node-get-journal-mqm98hvn-18",
          "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9du8z-8",
          "dataType": "JournalRef",
          "sourceHandle": "journal",
          "targetHandle": "value"
        },
        {
          "kind": "data",
          "source": "on-connect-event",
          "target": "node-get-journal-mqrk8yrn-121",
          "dataType": "DeviceRef",
          "sourceHandle": "device",
          "targetHandle": "device"
        },
        {
          "kind": "exec",
          "source": "node-is-valid-mqm97w5v-17",
          "target": "board-mqrk8res-sfp1k7n9",
          "sourceHandle": "exec-false-out",
          "targetHandle": "exec-in"
        },
        {
          "kind": "data",
          "source": "node-get-journal-mqrk8yrn-121",
          "target": "board-mqrk8res-sfp1k7n9",
          "dataType": "JournalRef",
          "sourceHandle": "journal",
          "targetHandle": "value"
        }
      ]
    },
    "loops": {
      "main": {
        "entry": "main-on-tick",
        "nodes": [
          {
            "id": "main-on-tick",
            "blockKind": "custom",
            "position": {
              "x": -2744,
              "y": -824
            },
            "label": "onTick",
            "nodeKind": "event",
            "system": true,
            "eventVariant": "loopTick"
          },
          {
            "id": "main-infinity",
            "blockKind": "custom",
            "position": {
              "x": 968,
              "y": -816
            },
            "label": "∞",
            "nodeKind": "loop-repeat",
            "system": true
          },
          {
            "id": "node-device-global-mqm0q2fd-14",
            "blockKind": "custom",
            "position": {
              "x": -2072,
              "y": -48
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "fn-3-block",
            "blockKind": "subgraph",
            "position": {
              "x": -2280,
              "y": -824
            },
            "label": "GetAudioStream::fn-3",
            "supportsAsync": true
          },
          {
            "id": "node-collect-samples-mqs2lopv-164",
            "blockKind": "custom",
            "position": {
              "x": -424,
              "y": -824
            },
            "label": "CollectSamples",
            "nodeKind": "collect-samples",
            "collectorConfig": {
              "bufferSize": 2048,
              "smoothingTimeConstant": 0.75,
              "windowSec": 3,
              "queueCapacity": 10
            }
          },
          {
            "id": "node-get-sample-mqs2mt0a-165",
            "blockKind": "custom",
            "position": {
              "x": -1816,
              "y": -824
            },
            "label": "GetSample",
            "nodeKind": "get-sample"
          },
          {
            "id": "node-get-spectral-analyser-mqs3gj4q-165",
            "blockKind": "custom",
            "position": {
              "x": -1672,
              "y": -160
            },
            "label": "GetSpectralAnalyser",
            "nodeKind": "get-spectral-analyser"
          },
          {
            "id": "node-get-fft-frame-mqs3h75e-166",
            "blockKind": "custom",
            "position": {
              "x": -1352,
              "y": -824
            },
            "label": "GetFFTFrame",
            "nodeKind": "get-fft-frame"
          },
          {
            "id": "node-collect-fft-frames-mqs3hhnu-167",
            "blockKind": "custom",
            "position": {
              "x": -888,
              "y": -824
            },
            "label": "CollectFftFrames",
            "nodeKind": "collect-fft-frames",
            "collectorConfig": {
              "bufferSize": 2048,
              "smoothingTimeConstant": 0.75,
              "windowSec": 3,
              "queueCapacity": 10
            }
          },
          {
            "id": "node-variable-get-var-JournalRef-mqm9dl4a-6-mqs51rew-13",
            "blockKind": "custom",
            "position": {
              "x": 1896,
              "y": -1104
            },
            "label": "journal1",
            "nodeKind": "variable-get",
            "variableId": "var-JournalRef-mqm9dl4a-6"
          },
          {
            "id": "fn-1-block",
            "blockKind": "subgraph",
            "position": {
              "x": 1432,
              "y": -760
            },
            "label": "StartRecording::fn-1",
            "supportsAsync": true
          },
          {
            "id": "fn-3-block-2",
            "blockKind": "subgraph",
            "position": {
              "x": 968,
              "y": -688
            },
            "label": "GetAudioStream::fn-3",
            "supportsAsync": true
          },
          {
            "id": "node-device-global-mqs5ibg8-126",
            "blockKind": "custom",
            "position": {
              "x": 552,
              "y": -832
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "board-mqs5v7w1-9c8xw62e",
            "blockKind": "custom",
            "position": {
              "x": 3472,
              "y": -520
            },
            "label": "PublishReport",
            "nodeKind": "publish-report"
          },
          {
            "id": "node-device-global-mqs6hsz3-170",
            "blockKind": "custom",
            "position": {
              "x": -288,
              "y": -1080
            },
            "label": "GetDevice",
            "nodeKind": "device-global"
          },
          {
            "id": "node-get-recorder-mqs6hyo6-171",
            "blockKind": "custom",
            "position": {
              "x": 8,
              "y": -696
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          },
          {
            "id": "node-variable-get-var-JournalRef-mqm9dl4a-6-mqs6jso7-15",
            "blockKind": "custom",
            "position": {
              "x": 2184,
              "y": -432
            },
            "label": "journal1",
            "nodeKind": "variable-get",
            "variableId": "var-JournalRef-mqm9dl4a-6"
          },
          {
            "id": "node-get-spectral-analyser-mqs6uey7-173",
            "blockKind": "custom",
            "position": {
              "x": 1080,
              "y": -1072
            },
            "label": "GetSpectralAnalyser",
            "nodeKind": "get-spectral-analyser"
          },
          {
            "id": "node-make-fft-trends-policy-mqs6wrpr-175",
            "blockKind": "custom",
            "position": {
              "x": 1672,
              "y": -624
            },
            "label": "MakeFftTrendsPolicy",
            "nodeKind": "make-fft-trends-policy",
            "fftTrendsPolicy": {
              "detectionMode": "auto",
              "measurementsCount": 20,
              "intervalMs": 500,
              "minConfidence": 0.55,
              "minRms": 0.02,
              "enabledTemplateKeys": [
                "DRONE_TIGHT",
                "WIND",
                "QUIET",
                "TRAFFIC",
                "BIRDS",
                "VOICE"
              ]
            },
            "pure": true
          },
          {
            "id": "node-sequence-gate-v20-async",
            "blockKind": "custom",
            "position": {
              "x": 504,
              "y": -704
            },
            "label": "Sequence",
            "nodeKind": "sequence",
            "sequenceConfig": {
              "thenCount": 4,
              "parallelAsync": false,
              "latentThen": true
            }
          },
          {
            "id": "fn-beta-async-upload-pipeline-block",
            "blockKind": "subgraph",
            "position": {
              "x": 968,
              "y": -944
            },
            "label": "Upload pipeline::fn-beta-async-upload-pipeline",
            "supportsAsync": true
          },
          {
            "id": "fn-beta-trends-publish-block",
            "blockKind": "subgraph",
            "position": {
              "x": 968,
              "y": -560
            },
            "label": "Trends publish::fn-beta-trends-publish",
            "supportsAsync": true
          },
          {
            "id": "fn-beta-recording-gate-block",
            "blockKind": "subgraph",
            "position": {
              "x": 40,
              "y": -824
            },
            "label": "Recording gate::fn-beta-recording-gate",
            "supportsAsync": true
          }
        ],
        "edges": [
          {
            "source": "main-on-tick",
            "sourceHandle": "exec-out",
            "target": "fn-3-block",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-3-block",
            "sourceHandle": "exec-out",
            "target": "node-get-sample-mqs2mt0a-165",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-3-block",
            "sourceHandle": "data-out",
            "target": "node-get-sample-mqs2mt0a-165",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "node-get-spectral-analyser-mqs3gj4q-165",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-sample-mqs2mt0a-165",
            "sourceHandle": "sample",
            "target": "node-get-fft-frame-mqs3h75e-166",
            "targetHandle": "sample",
            "kind": "data",
            "dataType": "AudioSampleRef"
          },
          {
            "source": "node-get-sample-mqs2mt0a-165",
            "sourceHandle": "exec-out",
            "target": "node-get-fft-frame-mqs3h75e-166",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-spectral-analyser-mqs3gj4q-165",
            "sourceHandle": "analyser",
            "target": "node-collect-fft-frames-mqs3hhnu-167",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-get-fft-frame-mqs3h75e-166",
            "sourceHandle": "exec-out",
            "target": "node-collect-fft-frames-mqs3hhnu-167",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-fft-frame-mqs3h75e-166",
            "sourceHandle": "frame",
            "target": "node-collect-fft-frames-mqs3hhnu-167",
            "targetHandle": "frame",
            "kind": "data",
            "dataType": "FftFrameRef"
          },
          {
            "source": "node-device-global-mqm0q2fd-14",
            "sourceHandle": "device",
            "target": "fn-beta-recording-gate-block",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-collect-fft-frames-mqs3hhnu-167",
            "sourceHandle": "exec-out",
            "target": "node-collect-samples-mqs2lopv-164",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-sample-mqs2mt0a-165",
            "sourceHandle": "sample",
            "target": "node-collect-samples-mqs2lopv-164",
            "targetHandle": "sample",
            "kind": "data",
            "dataType": "AudioSampleRef"
          },
          {
            "source": "node-collect-samples-mqs2lopv-164",
            "sourceHandle": "batches",
            "target": "fn-beta-recording-gate-block",
            "targetHandle": "samples",
            "kind": "data",
            "dataType": "AudioSampleRefList"
          },
          {
            "source": "node-collect-samples-mqs2lopv-164",
            "sourceHandle": "exec-out",
            "target": "fn-beta-recording-gate-block",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-recording-gate-block",
            "sourceHandle": "exec-false-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-recording-gate-block",
            "sourceHandle": "track",
            "target": "fn-beta-async-upload-pipeline-block",
            "targetHandle": "track",
            "kind": "data",
            "dataType": "TrackRef"
          },
          {
            "source": "fn-3-block-2",
            "sourceHandle": "data-out",
            "target": "fn-1-block",
            "targetHandle": "stream",
            "kind": "data",
            "dataType": "AudioStreamRef"
          },
          {
            "source": "node-device-global-mqs5ibg8-126",
            "sourceHandle": "device",
            "target": "fn-1-block",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "fn-3-block-2",
            "sourceHandle": "exec-out",
            "target": "fn-1-block",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-async-upload-pipeline-block",
            "sourceHandle": "report",
            "target": "board-mqs5v7w1-9c8xw62e",
            "targetHandle": "report",
            "kind": "data",
            "dataType": "ReportRef"
          },
          {
            "source": "node-variable-get-var-JournalRef-mqm9dl4a-6-mqs51rew-13",
            "sourceHandle": "value",
            "target": "fn-beta-trends-publish-block",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "fn-beta-trends-publish-block",
            "sourceHandle": "reporter",
            "target": "fn-beta-async-upload-pipeline-block",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "node-device-global-mqs6hsz3-170",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqs6hyo6-171",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-recorder-mqs6hyo6-171",
            "sourceHandle": "recorder",
            "target": "fn-beta-recording-gate-block",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-variable-get-var-JournalRef-mqm9dl4a-6-mqs6jso7-15",
            "sourceHandle": "value",
            "target": "fn-beta-trends-publish-block",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-variable-get-var-JournalRef-mqm9dl4a-6-mqs6jso7-15",
            "sourceHandle": "value",
            "target": "board-mqs5v7w1-9c8xw62e",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-device-global-mqs6hsz3-170",
            "sourceHandle": "device",
            "target": "node-get-spectral-analyser-mqs6uey7-173",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-spectral-analyser-mqs6uey7-173",
            "sourceHandle": "analyser",
            "target": "fn-beta-trends-publish-block",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "node-make-fft-trends-policy-mqs6wrpr-175",
            "sourceHandle": "policy",
            "target": "fn-beta-trends-publish-block",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "FftTrendsPolicy"
          },
          {
            "source": "node-sequence-gate-v20-async",
            "sourceHandle": "then-2",
            "target": "fn-beta-trends-publish-block",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-sequence-gate-v20-async",
            "sourceHandle": "then-3",
            "target": "fn-3-block-2",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-sequence-gate-v20-async",
            "sourceHandle": "exec-out",
            "target": "main-infinity",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "kind": "data",
            "source": "node-get-recorder-mqs6hyo6-171",
            "sourceHandle": "recorder",
            "target": "node-collect-samples-mqs2lopv-164",
            "targetHandle": "recorder",
            "dataType": "RecorderRef"
          },
          {
            "kind": "exec",
            "source": "fn-beta-recording-gate-block",
            "sourceHandle": "exec-out",
            "target": "node-sequence-gate-v20-async",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-sequence-gate-v20-async",
            "sourceHandle": "then-0",
            "target": "fn-beta-async-upload-pipeline-block",
            "targetHandle": "exec-in"
          }
        ]
      },
      "alarm": {
        "entry": "alarm-on-tick",
        "nodes": [
          {
            "id": "alarm-on-tick",
            "label": "onTick",
            "system": true,
            "nodeKind": "event",
            "position": {
              "x": 40,
              "y": 184
            },
            "blockKind": "custom",
            "eventVariant": "loopTick"
          },
          {
            "id": "alarm-infinity",
            "label": "∞",
            "system": true,
            "nodeKind": "loop-repeat",
            "position": {
              "x": 504,
              "y": 184
            },
            "blockKind": "custom"
          }
        ],
        "edges": [
          {
            "kind": "exec",
            "source": "alarm-on-tick",
            "target": "alarm-infinity",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          }
        ]
      }
    },
    "triggers": {
      "onStop": {
        "entry": "on-stop-event",
        "nodes": [
          {
            "id": "on-stop-event",
            "label": "On stop",
            "system": true,
            "nodeKind": "event",
            "position": {
              "x": 104,
              "y": 48
            },
            "blockKind": "custom",
            "eventVariant": "handler"
          },
          {
            "id": "node-is-valid-mqm9nw3u-21",
            "label": "isValid",
            "nodeKind": "is-valid",
            "position": {
              "x": 568,
              "y": 48
            },
            "blockKind": "custom"
          },
          {
            "id": "node-stop-streaming-mqm9ofcy-22",
            "label": "StopStreaming",
            "nodeKind": "stop-streaming",
            "position": {
              "x": 1032,
              "y": 48
            },
            "blockKind": "custom"
          },
          {
            "id": "node-device-global-mvp-onstop-1",
            "label": "GetDevice",
            "nodeKind": "device-global",
            "position": {
              "x": -120,
              "y": 184
            },
            "blockKind": "custom"
          },
          {
            "id": "node-get-microphone-mvp-onstop-1",
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "position": {
              "x": 56,
              "y": 312
            },
            "blockKind": "custom",
            "microphoneId": "0928f245e15f012de6b0d9e32f70efd5e6bc3957af6381c2b28da7536d150c04"
          }
        ],
        "edges": [
          {
            "kind": "exec",
            "source": "on-stop-event",
            "target": "node-is-valid-mqm9nw3u-21",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-is-valid-mqm9nw3u-21",
            "target": "node-stop-streaming-mqm9ofcy-22",
            "sourceHandle": "exec-true-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "data",
            "source": "node-device-global-mvp-onstop-1",
            "target": "node-get-microphone-mvp-onstop-1",
            "dataType": "DeviceRef",
            "sourceHandle": "device",
            "targetHandle": "device"
          }
        ]
      },
      "onDisconnect": {
        "entry": "on-disconnect-event",
        "nodes": [
          {
            "id": "on-disconnect-event",
            "label": "On disconnect",
            "system": true,
            "nodeKind": "event",
            "position": {
              "x": -96,
              "y": -128
            },
            "blockKind": "custom",
            "eventVariant": "handler"
          },
          {
            "id": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "label": "journal1",
            "nodeKind": "variable-set",
            "position": {
              "x": 368,
              "y": -128
            },
            "blockKind": "custom",
            "variableId": "var-JournalRef-mqm9dl4a-6"
          },
          {
            "id": "node-device-global-mqm9pz9v-23",
            "label": "GetDevice",
            "nodeKind": "device-global",
            "position": {
              "x": -104,
              "y": 88
            },
            "blockKind": "custom"
          },
          {
            "id": "node-get-journal-mqm9q43m-24",
            "label": "GetJournal",
            "nodeKind": "get-journal",
            "position": {
              "x": 184,
              "y": 8
            },
            "blockKind": "custom"
          }
        ],
        "edges": [
          {
            "kind": "data",
            "source": "node-device-global-mqm9pz9v-23",
            "target": "node-get-journal-mqm9q43m-24",
            "dataType": "DeviceRef",
            "sourceHandle": "device",
            "targetHandle": "device"
          },
          {
            "kind": "exec",
            "source": "on-disconnect-event",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "data",
            "source": "node-get-journal-mqm9q43m-24",
            "target": "node-variable-set-var-JournalRef-mqm9dl4a-6-mqm9pmz6-12",
            "dataType": "JournalRef",
            "sourceHandle": "journal",
            "targetHandle": "value"
          }
        ]
      },
      "custom": []
    },
    "functions": [
      {
        "id": "fn-3",
        "name": "GetAudioStream",
        "edges": [
          {
            "kind": "data",
            "source": "node-device-global-mqrtadee-143",
            "target": "node-get-microphone-mqrtaojo-144",
            "dataType": "DeviceRef",
            "sourceHandle": "device",
            "targetHandle": "device"
          },
          {
            "kind": "exec",
            "source": "fn-3-input",
            "target": "node-get-microphone-mqrtaojo-144",
            "sourceHandle": "exec-in",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-get-microphone-mqrtaojo-144",
            "target": "node-is-valid-mqrtb1vo-145",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "data",
            "source": "node-get-microphone-mqrtaojo-144",
            "target": "node-is-valid-mqrtb1vo-145",
            "dataType": "MicrophoneRef",
            "sourceHandle": "microphone",
            "targetHandle": "value"
          },
          {
            "kind": "data",
            "source": "node-get-microphone-mqrtaojo-144",
            "target": "node-get-audio-stream-mqrtbjp1-146",
            "dataType": "MicrophoneRef",
            "sourceHandle": "microphone",
            "targetHandle": "microphone"
          },
          {
            "kind": "exec",
            "source": "node-is-valid-mqrtb1vo-145",
            "target": "node-get-audio-stream-mqrtbjp1-146",
            "sourceHandle": "exec-true-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-get-audio-stream-mqrtbjp1-146",
            "target": "node-is-valid-mqrtbtth-147",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-is-valid-mqrtbtth-147",
            "target": "fn-3-output",
            "sourceHandle": "exec-true-out",
            "targetHandle": "exec-out"
          },
          {
            "kind": "exec",
            "source": "node-is-valid-mqrtbtth-147",
            "target": "node-stop-runtime-mqrtc7wk-148",
            "sourceHandle": "exec-false-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-is-valid-mqrtb1vo-145",
            "target": "node-stop-runtime-mqrtc7wk-148",
            "sourceHandle": "exec-false-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "data",
            "source": "node-get-audio-stream-mqrtbjp1-146",
            "target": "fn-3-output",
            "dataType": "AudioStreamRef",
            "sourceHandle": "stream",
            "targetHandle": "data-out"
          }
        ],
        "entry": "fn-3-input",
        "nodes": [
          {
            "id": "fn-3-input",
            "label": "Input",
            "system": true,
            "nodeKind": "function-input",
            "position": {
              "x": -200,
              "y": 200
            },
            "blockKind": "custom"
          },
          {
            "id": "fn-3-output",
            "label": "Output",
            "system": true,
            "nodeKind": "function-output",
            "position": {
              "x": 2120,
              "y": 264
            },
            "blockKind": "custom"
          },
          {
            "id": "node-device-global-mqrtadee-143",
            "label": "GetDevice",
            "nodeKind": "device-global",
            "position": {
              "x": -200,
              "y": 328
            },
            "blockKind": "custom"
          },
          {
            "id": "node-get-microphone-mqrtaojo-144",
            "label": "GetMicrophone",
            "nodeKind": "get-microphone",
            "position": {
              "x": 264,
              "y": 200
            },
            "blockKind": "custom"
          },
          {
            "id": "node-is-valid-mqrtb1vo-145",
            "label": "isValid",
            "nodeKind": "is-valid",
            "position": {
              "x": 728,
              "y": 200
            },
            "blockKind": "custom"
          },
          {
            "id": "node-get-audio-stream-mqrtbjp1-146",
            "label": "GetAudioStream",
            "nodeKind": "get-audio-stream",
            "position": {
              "x": 1192,
              "y": 248
            },
            "blockKind": "custom"
          },
          {
            "id": "node-is-valid-mqrtbtth-147",
            "label": "isValid",
            "nodeKind": "is-valid",
            "position": {
              "x": 1656,
              "y": 248
            },
            "blockKind": "custom"
          },
          {
            "id": "node-stop-runtime-mqrtc7wk-148",
            "label": "StopRuntime",
            "nodeKind": "stop-runtime",
            "position": {
              "x": 2120,
              "y": 136
            },
            "blockKind": "custom"
          }
        ],
        "inputPins": [
          {
            "id": "exec-in",
            "kind": "exec",
            "name": "exec-in"
          }
        ],
        "outputPins": [
          {
            "id": "exec-out",
            "kind": "exec",
            "name": "exec-out"
          },
          {
            "id": "data-out",
            "kind": "data",
            "name": "data-out",
            "socketType": "AudioStreamRef"
          }
        ]
      },
      {
        "id": "fn-1",
        "name": "StartRecording",
        "edges": [
          {
            "kind": "exec",
            "source": "node-get-recorder-mqmo3mba-31",
            "target": "node-start-recording-bootstrap-v08-2",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-in"
          },
          {
            "kind": "data",
            "source": "board-mqrklt5g-mwcrwuv3",
            "target": "node-start-recording-bootstrap-v08-2",
            "dataType": "RecordingPolicy",
            "sourceHandle": "policy",
            "targetHandle": "policy"
          },
          {
            "kind": "data",
            "source": "node-get-recorder-mqmo3mba-31",
            "target": "node-start-recording-bootstrap-v08-2",
            "dataType": "RecorderRef",
            "sourceHandle": "recorder",
            "targetHandle": "recorder"
          },
          {
            "kind": "data",
            "source": "fn-1-input",
            "target": "node-get-recorder-mqmo3mba-31",
            "dataType": "DeviceRef",
            "sourceHandle": "device",
            "targetHandle": "device"
          },
          {
            "kind": "data",
            "source": "fn-1-input",
            "target": "node-start-recording-bootstrap-v08-2",
            "dataType": "AudioStreamRef",
            "sourceHandle": "stream",
            "targetHandle": "stream"
          },
          {
            "kind": "exec",
            "source": "fn-1-input",
            "target": "node-get-recorder-mqmo3mba-31",
            "sourceHandle": "exec-in",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-start-recording-bootstrap-v08-2",
            "target": "fn-1-output",
            "sourceHandle": "exec-out",
            "targetHandle": "exec-out"
          },
          {
            "kind": "data",
            "source": "node-start-recording-bootstrap-v08-2",
            "target": "fn-1-output",
            "dataType": "RecorderRef",
            "sourceHandle": "recorder",
            "targetHandle": "data-out"
          }
        ],
        "entry": "fn-1-input",
        "nodes": [
          {
            "id": "fn-1-input",
            "label": "Input",
            "system": true,
            "nodeKind": "function-input",
            "position": {
              "x": -1416,
              "y": -536
            },
            "blockKind": "custom"
          },
          {
            "id": "fn-1-output",
            "label": "Output",
            "system": true,
            "nodeKind": "function-output",
            "position": {
              "x": -24,
              "y": -536
            },
            "blockKind": "custom"
          },
          {
            "id": "node-get-recorder-mqmo3mba-31",
            "label": "GetRecorder",
            "nodeKind": "get-recorder",
            "position": {
              "x": -952,
              "y": -536
            },
            "blockKind": "custom"
          },
          {
            "id": "node-start-recording-bootstrap-v08-2",
            "label": "StartRecording (bootstrap)",
            "nodeKind": "start-recording",
            "position": {
              "x": -488,
              "y": -536
            },
            "blockKind": "custom",
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "board-mqrklt5g-mwcrwuv3",
            "pure": true,
            "label": "MakeRecordingPolicy",
            "nodeKind": "make-recording-policy",
            "position": {
              "x": -960,
              "y": -336
            },
            "blockKind": "custom",
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          }
        ],
        "inputPins": [
          {
            "id": "exec-in",
            "kind": "exec",
            "name": "exec-in"
          },
          {
            "id": "device",
            "kind": "data",
            "name": "device",
            "socketType": "DeviceRef"
          },
          {
            "id": "stream",
            "kind": "data",
            "name": "stream",
            "socketType": "AudioStreamRef"
          }
        ],
        "outputPins": [
          {
            "id": "exec-out",
            "kind": "exec",
            "name": "exec-out"
          },
          {
            "id": "data-out",
            "kind": "data",
            "name": "data-out",
            "socketType": "RecorderRef"
          }
        ]
      },
      {
        "id": "fn-beta-async-upload-pipeline",
        "name": "Upload pipeline",
        "entry": "fn-beta-async-upload-pipeline-input",
        "nodes": [
          {
            "id": "fn-beta-async-upload-pipeline-input",
            "blockKind": "custom",
            "position": {
              "x": 40,
              "y": -576
            },
            "label": "Input",
            "nodeKind": "function-input",
            "system": true
          },
          {
            "id": "fn-beta-async-upload-pipeline-output",
            "blockKind": "custom",
            "position": {
              "x": 520,
              "y": 160
            },
            "label": "Output",
            "nodeKind": "function-output",
            "system": true
          },
          {
            "id": "node-make-report-from-track-mqs54kgw-177",
            "blockKind": "custom",
            "position": {
              "x": 3088,
              "y": -648
            },
            "label": "MakeReportFromTrack",
            "nodeKind": "make-report-from-track"
          },
          {
            "id": "node-start-async-job-v20",
            "blockKind": "custom",
            "position": {
              "x": 504,
              "y": -576
            },
            "label": "StartAsyncJob",
            "nodeKind": "start-async-job",
            "asyncJobConfig": {
              "jobKind": "track-upload",
              "awaitTimeoutMs": 30000
            },
            "supportsAsync": true
          },
          {
            "id": "node-on-async-resolved-v20",
            "blockKind": "custom",
            "position": {
              "x": 760,
              "y": -496
            },
            "label": "OnAsyncResolved",
            "nodeKind": "on-async-resolved"
          }
        ],
        "edges": [
          {
            "source": "node-start-async-job-v20",
            "sourceHandle": "promise",
            "target": "node-on-async-resolved-v20",
            "targetHandle": "promise",
            "kind": "data",
            "dataType": "PromiseRef"
          },
          {
            "source": "node-on-async-resolved-v20",
            "sourceHandle": "event-out",
            "target": "node-make-report-from-track-mqs54kgw-177",
            "targetHandle": "exec-in",
            "kind": "event"
          },
          {
            "source": "fn-beta-async-upload-pipeline-input",
            "sourceHandle": "exec-in",
            "target": "node-start-async-job-v20",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-async-upload-pipeline-input",
            "sourceHandle": "track",
            "target": "node-make-report-from-track-mqs54kgw-177",
            "targetHandle": "track",
            "kind": "data",
            "dataType": "TrackRef"
          },
          {
            "source": "node-make-report-from-track-mqs54kgw-177",
            "sourceHandle": "report",
            "target": "fn-beta-async-upload-pipeline-output",
            "targetHandle": "report",
            "kind": "data",
            "dataType": "ReportRef"
          },
          {
            "source": "fn-beta-async-upload-pipeline-input",
            "sourceHandle": "reporter",
            "target": "node-make-report-from-track-mqs54kgw-177",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "fn-beta-async-upload-pipeline-input",
            "sourceHandle": "exec-in",
            "target": "node-start-async-job-v20",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-async-upload-pipeline-input",
            "sourceHandle": "track",
            "target": "node-start-async-job-v20",
            "targetHandle": "track",
            "kind": "data",
            "dataType": "TrackRef"
          }
        ],
        "inputPins": [
          {
            "id": "exec-in",
            "name": "exec-in",
            "kind": "exec"
          },
          {
            "id": "track",
            "name": "track",
            "kind": "data",
            "socketType": "TrackRef"
          },
          {
            "id": "reporter",
            "name": "reporter",
            "kind": "data",
            "socketType": "ReporterRef"
          }
        ],
        "outputPins": [
          {
            "id": "exec-out",
            "name": "exec-out",
            "kind": "exec"
          },
          {
            "id": "report",
            "name": "report",
            "kind": "data",
            "socketType": "ReportRef"
          }
        ],
        "description": "StartAsyncJob → detached MakeReportFromTrack"
      },
      {
        "id": "fn-beta-trends-publish",
        "name": "Trends publish",
        "entry": "fn-beta-trends-publish-input",
        "nodes": [
          {
            "id": "fn-beta-trends-publish-input",
            "blockKind": "custom",
            "position": {
              "x": 40,
              "y": -864
            },
            "label": "Input",
            "nodeKind": "function-input",
            "system": true
          },
          {
            "id": "fn-beta-trends-publish-output",
            "blockKind": "custom",
            "position": {
              "x": 520,
              "y": 160
            },
            "label": "Output",
            "nodeKind": "function-output",
            "system": true
          },
          {
            "id": "node-make-report-from-analysis-mqma356z-34",
            "blockKind": "custom",
            "position": {
              "x": 1432,
              "y": -864
            },
            "label": "MakeReportFromAnalysis",
            "nodeKind": "make-report-from-analysis",
            "supportsAsync": true
          },
          {
            "id": "node-publish-report-mqma49xv-35",
            "blockKind": "custom",
            "position": {
              "x": 1896,
              "y": -864
            },
            "label": "PublishReport",
            "nodeKind": "publish-report",
            "supportsAsync": true
          },
          {
            "id": "node-get-reporter-mqs5wkzi-169",
            "blockKind": "custom",
            "position": {
              "x": 2136,
              "y": -1048
            },
            "label": "GetReporter",
            "nodeKind": "get-reporter"
          },
          {
            "id": "node-flush-spectral-analyser-mqs6tcs6-172",
            "blockKind": "custom",
            "position": {
              "x": 504,
              "y": -864
            },
            "label": "FlushSpectralAnalyser",
            "nodeKind": "flush-spectral-analyser",
            "supportsAsync": true
          },
          {
            "id": "node-make-fft-trends-analysis-mqs6vdme-174",
            "blockKind": "custom",
            "position": {
              "x": 968,
              "y": -864
            },
            "label": "MakeFftTrendsAnalysis",
            "nodeKind": "make-fft-trends-analysis",
            "supportsAsync": true
          }
        ],
        "edges": [
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "report",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "report",
            "kind": "data",
            "dataType": "ReportRef"
          },
          {
            "source": "node-make-report-from-analysis-mqma356z-34",
            "sourceHandle": "exec-out",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-get-reporter-mqs5wkzi-169",
            "sourceHandle": "reporter",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "node-flush-spectral-analyser-mqs6tcs6-172",
            "sourceHandle": "frames",
            "target": "node-make-fft-trends-analysis-mqs6vdme-174",
            "targetHandle": "frames",
            "kind": "data",
            "dataType": "FftFrameRefList"
          },
          {
            "source": "node-make-fft-trends-analysis-mqs6vdme-174",
            "sourceHandle": "analysis",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "analysis",
            "kind": "data",
            "dataType": "FftTrendAnalysisRef"
          },
          {
            "source": "node-flush-spectral-analyser-mqs6tcs6-172",
            "sourceHandle": "exec-out",
            "target": "node-make-fft-trends-analysis-mqs6vdme-174",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-make-fft-trends-analysis-mqs6vdme-174",
            "sourceHandle": "exec-out",
            "target": "node-make-report-from-analysis-mqma356z-34",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "exec-in",
            "target": "node-flush-spectral-analyser-mqs6tcs6-172",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "journal",
            "target": "node-get-reporter-mqs5wkzi-169",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "node-get-reporter-mqs5wkzi-169",
            "sourceHandle": "reporter",
            "target": "fn-beta-trends-publish-output",
            "targetHandle": "reporter",
            "kind": "data",
            "dataType": "ReporterRef"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "journal",
            "target": "node-publish-report-mqma49xv-35",
            "targetHandle": "journal",
            "kind": "data",
            "dataType": "JournalRef"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "analyser",
            "target": "node-flush-spectral-analyser-mqs6tcs6-172",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "analyser",
            "target": "node-make-fft-trends-analysis-mqs6vdme-174",
            "targetHandle": "analyser",
            "kind": "data",
            "dataType": "SpectralAnalyserRef"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "policy",
            "target": "node-make-fft-trends-analysis-mqs6vdme-174",
            "targetHandle": "policy",
            "kind": "data",
            "dataType": "FftTrendsPolicy"
          },
          {
            "source": "fn-beta-trends-publish-input",
            "sourceHandle": "exec-in",
            "target": "node-flush-spectral-analyser-mqs6tcs6-172",
            "targetHandle": "exec-in",
            "kind": "exec"
          }
        ],
        "inputPins": [
          {
            "id": "exec-in",
            "name": "exec-in",
            "kind": "exec"
          },
          {
            "id": "journal",
            "name": "journal",
            "kind": "data",
            "socketType": "JournalRef"
          },
          {
            "id": "analyser",
            "name": "analyser",
            "kind": "data",
            "socketType": "SpectralAnalyserRef"
          },
          {
            "id": "policy",
            "name": "policy",
            "kind": "data",
            "socketType": "FftTrendsPolicy"
          }
        ],
        "outputPins": [
          {
            "id": "exec-out",
            "name": "exec-out",
            "kind": "exec"
          },
          {
            "id": "reporter",
            "name": "reporter",
            "kind": "data",
            "socketType": "ReporterRef"
          }
        ],
        "description": "Flush FFT → classify → MakeReportFromAnalysis → PublishReport"
      },
      {
        "id": "fn-beta-recording-gate",
        "name": "Recording gate",
        "entry": "fn-beta-recording-gate-input",
        "nodes": [
          {
            "id": "fn-beta-recording-gate-input",
            "blockKind": "custom",
            "position": {
              "x": -504,
              "y": -648
            },
            "label": "Input",
            "nodeKind": "function-input",
            "system": true
          },
          {
            "id": "fn-beta-recording-gate-output",
            "blockKind": "custom",
            "position": {
              "x": 1352,
              "y": -648
            },
            "label": "Output",
            "nodeKind": "function-output",
            "system": true
          },
          {
            "id": "node-make-track-mqmcipn5-28",
            "blockKind": "custom",
            "position": {
              "x": 888,
              "y": -648
            },
            "label": "MakeTrack",
            "nodeKind": "make-track",
            "supportsAsync": true
          },
          {
            "id": "node-is-recording-window-full-mqmo40ie-32",
            "blockKind": "custom",
            "position": {
              "x": -40,
              "y": -648
            },
            "label": "IsRecordingWindowFull",
            "nodeKind": "is-recording-window-full",
            "recordingPolicy": {
              "windowSec": 5,
              "captureFormat": "wav"
            }
          },
          {
            "id": "node-stop-recording-mqmod4yf-35",
            "blockKind": "custom",
            "position": {
              "x": 424,
              "y": -648
            },
            "label": "StopRecording",
            "nodeKind": "stop-recording",
            "supportsAsync": true
          },
          {
            "id": "node-get-recorder-mqs3ir02-168",
            "blockKind": "custom",
            "position": {
              "x": -1800,
              "y": -72
            },
            "label": "GetRecorder",
            "nodeKind": "get-recorder"
          }
        ],
        "edges": [
          {
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "slice",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "slice",
            "kind": "data",
            "dataType": "RecordingSliceRef"
          },
          {
            "source": "node-get-recorder-mqs3ir02-168",
            "sourceHandle": "recorder",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "node-get-recorder-mqs3ir02-168",
            "sourceHandle": "recorder",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "fn-beta-recording-gate-input",
            "sourceHandle": "exec-in",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-false-out",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "exec-false-out",
            "kind": "exec"
          },
          {
            "source": "fn-beta-recording-gate-input",
            "sourceHandle": "device",
            "target": "node-get-recorder-mqs3ir02-168",
            "targetHandle": "device",
            "kind": "data",
            "dataType": "DeviceRef"
          },
          {
            "source": "node-get-recorder-mqs3ir02-168",
            "sourceHandle": "recorder",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "source": "fn-beta-recording-gate-input",
            "sourceHandle": "samples",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "samples",
            "kind": "data",
            "dataType": "AudioSampleRefList"
          },
          {
            "source": "fn-beta-recording-gate-input",
            "sourceHandle": "exec-in",
            "target": "node-is-recording-window-full-mqmo40ie-32",
            "targetHandle": "exec-in",
            "kind": "exec"
          },
          {
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-false-out",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "exec-false-out",
            "kind": "exec"
          },
          {
            "source": "node-make-track-mqmcipn5-28",
            "sourceHandle": "track",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "track",
            "kind": "data",
            "dataType": "TrackRef"
          },
          {
            "source": "fn-beta-recording-gate-input",
            "sourceHandle": "recorder",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "recorder",
            "kind": "data",
            "dataType": "RecorderRef"
          },
          {
            "kind": "exec",
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-true-out",
            "target": "node-stop-recording-mqmod4yf-35",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-stop-recording-mqmod4yf-35",
            "sourceHandle": "exec-out",
            "target": "node-make-track-mqmcipn5-28",
            "targetHandle": "exec-in"
          },
          {
            "kind": "exec",
            "source": "node-make-track-mqmcipn5-28",
            "sourceHandle": "exec-out",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "exec-out"
          },
          {
            "kind": "exec",
            "source": "node-is-recording-window-full-mqmo40ie-32",
            "sourceHandle": "exec-true-out",
            "target": "fn-beta-recording-gate-output",
            "targetHandle": "exec-true-out"
          }
        ],
        "inputPins": [
          {
            "id": "exec-in",
            "name": "exec-in",
            "kind": "exec"
          },
          {
            "id": "device",
            "name": "device",
            "kind": "data",
            "socketType": "DeviceRef"
          },
          {
            "id": "samples",
            "name": "samples",
            "kind": "data",
            "socketType": "AudioSampleRefList"
          },
          {
            "id": "recorder",
            "name": "recorder",
            "kind": "data",
            "socketType": "RecorderRef"
          }
        ],
        "outputPins": [
          {
            "id": "exec-false-out",
            "name": "exec-false-out",
            "kind": "exec"
          },
          {
            "id": "recorder",
            "name": "recorder",
            "kind": "data",
            "socketType": "RecorderRef"
          },
          {
            "id": "track",
            "name": "track",
            "kind": "data",
            "socketType": "TrackRef"
          },
          {
            "id": "exec-out",
            "name": "exec-out",
            "kind": "exec"
          },
          {
            "id": "exec-true-out",
            "name": "exec-true-out",
            "kind": "exec"
          }
        ],
        "description": "5 s window gate + MakeTrack"
      }
    ],
    "scheduled": [],
    "commentGroups": [
      {
        "id": "ucg-beta-main-orchestrator",
        "branch": "main",
        "title": "Orchestrator spine",
        "description": "Main tick → policy → functions → ∞",
        "frameColor": {
          "preset": "primary"
        },
        "rect": {
          "x": -2096,
          "y": -1104,
          "width": 4016,
          "height": 1184
        },
        "nodeIds": [
          "node-device-global-mqm0q2fd-14",
          "node-device-global-mqs5ibg8-126",
          "node-device-global-mqs6hsz3-170",
          "node-make-fft-trends-policy-mqs6wrpr-175"
        ]
      },
      {
        "id": "ucg-beta-fn-gate",
        "branch": "main",
        "title": "Function: recording gate",
        "description": "5 s window, MakeTrack, restart recording",
        "frameColor": {
          "preset": "warning"
        },
        "rect": {
          "x": 16,
          "y": -848,
          "width": 272,
          "height": 152
        },
        "nodeIds": [
          "fn-beta-recording-gate-block"
        ]
      },
      {
        "id": "ucg-beta-fn-trends",
        "branch": "main",
        "title": "Function: trends publish",
        "description": "Spectral → FFT → classify → PublishReport",
        "frameColor": {
          "preset": "info"
        },
        "rect": {
          "x": -1840,
          "y": -1096,
          "width": 3168,
          "height": 1064
        },
        "nodeIds": [
          "node-get-sample-mqs2mt0a-165",
          "node-get-spectral-analyser-mqs3gj4q-165",
          "node-get-fft-frame-mqs3h75e-166",
          "node-collect-fft-frames-mqs3hhnu-167",
          "node-get-spectral-analyser-mqs6uey7-173",
          "fn-beta-trends-publish-block"
        ]
      },
      {
        "id": "ucg-beta-fn-policy",
        "branch": "main",
        "title": "Function: policy build",
        "description": "MakeRecordingPolicy + MakeFftTrendsPolicy",
        "frameColor": {
          "preset": "neutral"
        },
        "rect": {
          "x": 1648,
          "y": -648,
          "width": 272,
          "height": 152
        },
        "nodeIds": [
          "node-make-fft-trends-policy-mqs6wrpr-175"
        ]
      },
      {
        "id": "ucg-beta-async-upload",
        "branch": "main",
        "title": "⑤ Отправка в фоне",
        "description": "StartAsyncJob track-upload — не блокирует main tick",
        "frameColor": {
          "preset": "info"
        },
        "rect": {
          "x": 480,
          "y": -968,
          "width": 736,
          "height": 392
        },
        "nodeIds": [
          "node-sequence-gate-v20-async",
          "fn-beta-async-upload-pipeline-block"
        ]
      },
      {
        "id": "ucg-beta-async-detached",
        "branch": "main",
        "title": "⑥ Отчёт дрон (detached)",
        "description": "Detached on-async-resolved → MakeReportFromTrack → PublishReport",
        "frameColor": {
          "preset": "accent"
        },
        "rect": {
          "x": 944,
          "y": -968,
          "width": 272,
          "height": 152
        },
        "nodeIds": [
          "fn-beta-async-upload-pipeline-block"
        ]
      }
    ],
    "variables": [
      {
        "id": "var-JournalRef-mqm9dl4a-6",
        "name": "journal1",
        "type": "JournalRef",
        "value": null
      }
    ]
  }
} as unknown as DeviceScenarioDocument;
