/**
 * AUTO-GENERATED by yarn comp:publish-catalog — do not edit by hand.
 * Sprint: `comp-mvp-async-v2-2026-06-25`
 * Regenerate: yarn comp:publish-catalog --id comp-mvp-async-v2-2026-06-25
 */
import type { UserCaseCatalogEntry } from './user-case-catalog-types.js';
import { getDefaultMvpMicrophoneAlphaAsyncV2Document } from '../graph/default-usercase-mvp-microphone-alpha-async-v2.js';
import { getDefaultMvpMicrophoneBetaAsyncV2Document } from '../graph/default-usercase-mvp-microphone-beta-async-v2.js';
import { getDefaultMvpMicrophoneGammaAsyncV2Document } from '../graph/default-usercase-mvp-microphone-gamma-async-v2.js';

/** Active competition forks in device-board UserCase picker (`tier: community`). */
export const COMMUNITY_COMPETITION_USER_CASE_ENTRIES: readonly UserCaseCatalogEntry[] = [
  {
    id: 'usercase-mvp-microphone-alpha-async-v2',
    title: 'Alpha: Live Observation Pipeline (async v2)',
    description: 'Competition async v2 — Act IIb narrative, StartAsyncJob visible on main. Operator journey + async story.',
    deviceKind: 'microphone',
    tier: 'community',
    layoutProfile: 'exec-lr-v1',
    branchCount: 6,
    functionCount: 4,
    loadDocument: getDefaultMvpMicrophoneAlphaAsyncV2Document,
  },
  {
    id: 'usercase-mvp-microphone-beta-async-v2',
    title: 'Beta: Measured modular UserCase (async v2 · winner)',
    description: 'Competition async v2 winner — fn-beta-async-upload-pipeline, poster ⑤⑥ cherry-pick on async groups.',
    deviceKind: 'microphone',
    tier: 'community',
    layoutProfile: 'exec-lr-v1',
    branchCount: 6,
    functionCount: 3,
    loadDocument: getDefaultMvpMicrophoneBetaAsyncV2Document,
  },
  {
    id: 'usercase-mvp-microphone-gamma-async-v2',
    title: 'Gamma: Poster UserCase (async v2)',
    description: 'Competition async v2 — poster ①–⑥, async upload + detached report as numbered steps.',
    deviceKind: 'microphone',
    tier: 'community',
    layoutProfile: 'exec-lr-v1',
    branchCount: 6,
    functionCount: 3,
    loadDocument: getDefaultMvpMicrophoneGammaAsyncV2Document,
  },
];
